/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Price } from './price';


export interface MedicineDtoAdmin { 
    code?: string;
    company?: Company;
    
    id?: number;
    medicineName?: string;
    price?: Price;
    
    quantityExsiting?: number;
    unit?: string;
    group?:string;

    // for display list:
    companyName?: String ;
    priceBought?:number;
    priceSell?:number;
   
    dateCreate?:Date;
}
