/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Medicine } from './medicine';


export interface Price { 
    boughtPrice?: number;
    dateApply?: Date;
    id?: number;
    medicine?: Medicine;
    medicineId?: number;
    sellForCompanyPrice?: number;
    sellForFarmPrice?: number;
    sellForPersonalPrice?: number;
}
