/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ReportDto { 
    amount?: number;
    boughtQuanity?: number;
    customerName?: string;
    dateSell?: string;
    exsitingQuantity?: number;
    medicineCode?: string;
    medicineName?: string;
    price?: number;
    total?: number;
    unit?: string;
}
