/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerDto } from './customerDto';
import { MedicineDto } from './medicineDto';
import { InvoiceDto } from './invoiceDto';


export interface SellOrderDto {
    customer?: CustomerDto;
    id?: number;
    listMedicines?: Array<MedicineDto>;
    listInvoice?: Array<InvoiceDto>;
    time?: Date;
    total?: number;
    seller?:String;
}
